### ISSUE TITLE
Function `mcrypt_create_iv()` is deprecated in PHP 7.1.0

### ISSUE THREAD

**Issue by wampiedriessen** [rchouinard/rych-random#3]
According to https://secure.php.net/mcrypt_create_iv. An appropriate alternative is the PHP function `random_bytes()`

**Comment by insaurabh** [comment]
This function was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.
[php documnetation](http://php.net/manual/en/function.mcrypt-create-iv.php)

user **random_bytes** — which Generates cryptographically secure pseudo-random bytes.


```
<?php
$bytes = random_bytes(5);
var_dump(bin2hex($bytes));
?>
```

`string(10) "385e33f741"`

Taken from php.net

**Comment by sergepavle** [comment]
Here is PR for this issue. Available for review:
https://github.com/rchouinard/rych-random/pull/5

**Comment by wampiedriessen** [comment]
This project seems to be no longer maintained.
